### ISSUE TITLE
Which BVH files to use from CMU cgspeed

### ISSUE THREAD

**Issue by hshreeshail** [jsan3386/avatar#2]
The CMU link from the project [page](https://jsan3386.github.io/avatar/) has 3 different types of BVH files of CMU's motion capture dataset:
1] 3dsMax-friendly BVH release
2] Daz-friendly BVH release
3] Motionbuilder-friendly BVH release

Which one of these should I use?

**Comment by hshreeshail** [comment]
I tried using a .bvh file from the 3dsMax-friendly BVH release, and am getting the following error message
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\avatar\__init__.py", line 475, in execute
    retarget.retarget_addon(bone_corresp_file, file_path_bvh, obj, scn.skel_rig)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\addons\avatar\motion\retarget_motion\retarget.py", line 511, in retarget_addon
    trg_bone_length = trg_skel.pose.bones[list_bones_trg[bidx]].length
KeyError: 'bpy_prop_collection[key]: key "LeftUpLeg" not found'
```

**Comment by jsan3386** [comment]
I think is the 3) option. You can do several things to transfer bvh motion files to the avatar model: 1) use external addon http://diffeomorphic.blogspot.com/p/bvh-retargeter.html (my code is based on this addon) that can automatically detect bone correspondences, 2) go where the avatar addon is installed and check for the motion/rigs folder. There you can find bone correspondences between avatar model and other models, you can create a new file, for example cmu_3dsmax.txt and change bone names. Left column is avatar bone names, right column is bvh file bone names. Once you created this file, restart addon that should be detected automatically and you can use it as new option.
